version: '2.1'

services:
  app:
    image: 'network:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: highload
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_URL=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - spring.redis.host=redis

  db:
    image: 'postgres:16-alpine'
    container_name: db
    ports:
      - "8083:5432"
    volumes:
      - ./postgres-dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'" ]
      interval: 20s
      timeout: 3s
      retries: 3

  redis:
    image: 'redis:7.2.1'
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
